name: Tkinter GUI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          sudo apt-get update && sudo apt-get install -y xvfb  # Install virtual display

      - name: Run TicTacToe Tests
        run: |
          set -e  # Exit on first error
          xvfb-run --auto-servernum python -m unittest discover

      - name: Show Test Results
        if: always()
        run: cat test-results.log || echo "No test results available"
